language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
  matrix:
    - BRANCH=master LEVEL=6 EXT="--no-extensions" REPOSITORY="https://github.com/phpstan/phpstan.git"
    - BRANCH=0.6.4-fixed LEVEL=5 EXT="" REPOSITORY="https://github.com/fprochazka/phpstan.git"

php:
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - php -dphar.readonly=0 bin/compile -v --repository $REPOSITORY $EXT $BRANCH
  - php -dmemory_limit=2G ./tmp/phpstan-$BRANCH.phar analyse -l $LEVEL src
